version: "3.7"
services:

  node_1:
    image: bc-node:0.1
    container_name: node_1
    environment:
      - CURRENT_NODE_URL=http://node_1:3000
    ports:
      - "3001:3000"
    networks:
      app-net: {}
  
  node_2:
    image: bc-node:0.1
    container_name: node_2
    environment:
      - CURRENT_NODE_URL=http://node_2:3000
    ports:
      - "3002:3000"
    networks:
      app-net: {}

  node_3:
    image: bc-node:0.1
    container_name: node_3
    environment:
      - CURRENT_NODE_URL=http://node_3:3000
    ports:
      - "3003:3000"
    networks:
      app-net: {}

networks:
  app-net:
    external: true
    name: 'bc-net'